import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-back relative`}>
        {children}
        <footer className="absolute bottom-0 left-0 w-full z-[-1]">
          <figure>
            <img
              src="/mobile-bottom-shape.svg"
              className="w-full md:invisible"
              alt="large footer"
            />
            <img
              src="/bottom-shape.svg"
              className="invisible w-0 md:w-full md:visible"
              alt="mobile footer"
            />
          </figure>
        </footer>
      </body>
    </html>
  );
}
